package Main;

public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
        //connect();
        setTitle("Searching Page");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        SearchPage = new javax.swing.JPanel();
        SelectArea = new javax.swing.JLabel();
        AreaSelect = new javax.swing.JComboBox<>();
        selectBloodGroup = new javax.swing.JLabel();
        GroupSelect = new javax.swing.JComboBox<>();
        Search = new javax.swing.JButton();
        Return = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Search.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchPage.setPreferredSize(new java.awt.Dimension(766, 630));
        SearchPage.setLayout(null);

        SelectArea.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SelectArea.setText("Select Area");
        SearchPage.add(SelectArea);
        SelectArea.setBounds(550, 220, 160, 40);

        AreaSelect.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AreaSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rampura", "Malibag", "Motijheel", "Uttora", "Mohakhali", "Badda" }));
        AreaSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaSelectActionPerformed(evt);
            }
        });
        SearchPage.add(AreaSelect);
        AreaSelect.setBounds(550, 290, 150, 40);

        selectBloodGroup.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        selectBloodGroup.setText("Select Blood Group");
        SearchPage.add(selectBloodGroup);
        selectBloodGroup.setBounds(50, 220, 230, 30);

        GroupSelect.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GroupSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        GroupSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroupSelectActionPerformed(evt);
            }
        });
        SearchPage.add(GroupSelect);
        GroupSelect.setBounds(50, 290, 150, 40);

        Search.setBackground(new java.awt.Color(255, 255, 255));
        Search.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        SearchPage.add(Search);
        Search.setBounds(330, 540, 150, 50);

        Return.setBackground(new java.awt.Color(255, 255, 255));
        Return.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Return.setText("Return");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        SearchPage.add(Return);
        Return.setBounds(610, 560, 140, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/search_page.jpg"))); // NOI18N
        SearchPage.add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SearchPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SearchPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AreaSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaSelectActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        // TODO add your handling code here:
        Search.setVisible(false);
        FirstPage third = new FirstPage();
        third.setVisible(true);
        dispose();

    }//GEN-LAST:event_ReturnActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String Area = AreaSelect.getSelectedItem().toString();
        String Group = GroupSelect.getSelectedItem().toString();

        //Variables Search = new Variables(Area, Group);
        SearchInfo one = new SearchInfo(Area, Group);
        one.setVisible(true);
        dispose();
    }//GEN-LAST:event_SearchActionPerformed

    private void GroupSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GroupSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AreaSelect;
    private javax.swing.JComboBox<String> GroupSelect;
    private javax.swing.JButton Return;
    private javax.swing.JButton Search;
    private javax.swing.JPanel SearchPage;
    private javax.swing.JLabel SelectArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel selectBloodGroup;
    // End of variables declaration//GEN-END:variables
}
