package Main;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class UpdateInfo extends javax.swing.JFrame {

    /**
     * Creates new form UpdateInfo
     */
    public UpdateInfo() {
        initComponents();
        connect();
        setTitle("Updating Page");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdatePage = new javax.swing.JPanel();
        LastDonation = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        Return = new javax.swing.JButton();
        last_date = new javax.swing.JTextField();
        Check = new javax.swing.JButton();
        Nextdonation = new javax.swing.JTextField();
        IDINPUT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UpdatePage.setPreferredSize(new java.awt.Dimension(766, 630));
        UpdatePage.setLayout(null);

        LastDonation.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LastDonation.setText("Last Date of Donation (YYYY-MM-DD)");
        UpdatePage.add(LastDonation);
        LastDonation.setBounds(20, 140, 460, 40);

        Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        UpdatePage.add(Update);
        Update.setBounds(230, 470, 120, 50);

        Return.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Return.setText("Return");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        UpdatePage.add(Return);
        Return.setBounds(510, 560, 150, 50);
        UpdatePage.add(last_date);
        last_date.setBounds(20, 210, 200, 40);

        Check.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Check.setText("Check");
        Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckActionPerformed(evt);
            }
        });
        UpdatePage.add(Check);
        Check.setBounds(50, 470, 120, 50);
        UpdatePage.add(Nextdonation);
        Nextdonation.setBounds(20, 340, 220, 40);
        UpdatePage.add(IDINPUT);
        IDINPUT.setBounds(20, 90, 240, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Enter ID");
        UpdatePage.add(jLabel1);
        jLabel1.setBounds(20, 30, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Will be Eligible to Donate Blood");
        UpdatePage.add(jLabel2);
        jLabel2.setBounds(20, 270, 410, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/update_pic.jpg"))); // NOI18N
        UpdatePage.add(jLabel3);
        jLabel3.setBounds(0, 0, 770, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpdatePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpdatePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void connect() {

        try {

            Variables.myconnectionobj = DriverManager.getConnection("jdbc:derby://localhost:1527/BloodBank1", "admin1", "admin");

        } catch (SQLException ex) {
            //ex.printStackTrace();
        }
    }
    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        // TODO add your handling code here:
        UpdatePage.setVisible(false);
        Summary second = new Summary();
        second.setVisible(true);
        dispose();

    }//GEN-LAST:event_ReturnActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        int flag = 0;

        try { 
             Class.forName("com.mysql.jdbc.Driver");  
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/blooddonation","root","");  
        PreparedStatement stmt=con.prepareStatement("UPDATE `regdoner` SET `LAST_DATE_DONATION`= ?,`ELIGIBLE_TO_DONATE`=? WHERE `ID` = ?");  
        stmt.setString(1,last_date.getText());//1 specifies the first parameter in the query  
        stmt.setString(2,Nextdonation.getText());  
        stmt.setString(3,IDINPUT.getText());  
    
        int i=stmt.executeUpdate();  
        System.out.println(i+" records updated");  
        con.close(); 
            
   

        } catch (Exception e) {
            
            flag = 1;
        }
        
        if (flag == 0) {

            Component GUI = null;
            JOptionPane.showMessageDialog(GUI, "Successfully Updated.");
        } else {
            Component GUI = null;
            JOptionPane.showMessageDialog(GUI, "Unsuccessful. Please try again");
        }

    }//GEN-LAST:event_UpdateActionPerformed

    private void CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckActionPerformed
        // TODO add your handling code here:
        String Ldate = last_date.getText();
        check(Ldate);
    }//GEN-LAST:event_CheckActionPerformed
    void check(String date) {
        String oldDate = date;

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar c = Calendar.getInstance();
        try {

            c.setTime(sdf.parse(oldDate));
        } catch (ParseException e) {
           
        }

        c.add(Calendar.DAY_OF_MONTH, 120);

        String newDate = sdf.format(c.getTime());
        Variables.Lastdate = newDate;
        Nextdonation.setText(newDate);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Check;
    private javax.swing.JTextField IDINPUT;
    private javax.swing.JLabel LastDonation;
    private javax.swing.JTextField Nextdonation;
    private javax.swing.JButton Return;
    private javax.swing.JButton Update;
    private javax.swing.JPanel UpdatePage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField last_date;
    // End of variables declaration//GEN-END:variables
}
